---
title: Making Dot and Bubble Maps with ggplot
format:
  rfortherestofus-slides-revealjs:
    output-location: slide
---

### Dot Maps

::: {.notes}
https://www.theguardian.com/world/2023/oct/25/peru-pozuzo-austria-german-town-history

https://archive.is/5YfM1

https://brilliantmaps.com/lighthouses-gb-ire/
:::

```{r}
#| eval: false
#| echo: false
oregon_places <-
  get_decennial(
    geography = "place",
    state = "OR",
    variables = "P1_001N",
    geometry = TRUE,
    year = 2020
  ) |>
  st_centroid() |>
  select(NAME, value) |>
  set_names("name", "population", "geometry")

oregon_places |>
  write_sf("data/oregon_places.geojson")

oregon <-
  states() |>
  clean_names() |>
  filter(name == "Oregon")
```

```{r}
library(tidyverse)
library(tidycensus)
library(tigris)
library(janitor)
library(sf)
```

```{r}
#| output: false
oregon <-
  states() |>
  clean_names() |>
  filter(name == "Oregon")

oregon_places <-
  read_sf("data/oregon_places.geojson")
```

---

```{r}
#| output-location: fragment
oregon_places
```

---

```{r}
ggplot() +
  geom_sf(data = oregon, fill = "transparent") +
  geom_sf(data = oregon_places) +
  theme_void()
```

### Bubble Maps

::: {.notes}
https://www.axios.com/2025/02/24/where-college-educated-americans-are-moving

https://www.nytimes.com/2025/02/04/us/hurricane-helene-deaths.html

https://bsky.app/profile/infobeautiful.bsky.social/post/3lhe447wxan2j

https://www.nytimes.com/2025/02/08/world/europe/us-foreign-aid-freeze-wwk.html?smtyp=cur&smid=bsky-nytimes; https://show.rfor.us/qcd9tBSX

https://www.nytimes.com/interactive/2025/health/measles-outbreak-map.html

Show OBTN population map
:::

```{r}
ggplot() +
  geom_sf(data = oregon, fill = "transparent") +
  geom_sf(
    data = oregon_places,
    aes(size = population),
    alpha = 0.5
  ) +
  scale_size_continuous(range = c(1, 15)) +
  theme_void()
```

::: {.notes}
Show guide_circles() from {legendry} for alt legend: https://teunbrand.github.io/legendry/reference/guide_circles.html?q=size#null
:::



### Your Turn {.your-turn}

Turn your refguees choropleth map from before into a bubble map

```{r}
#| echo: false
library(sf)
library(tidyverse)

sf_use_s2(FALSE)

read_sf(
  "https://raw.githubusercontent.com/rfortherestofus/mapping-with-r-v2/refs/heads/main/data/refugees.geojson"
) |>
  filter(!st_is_empty(geometry)) |> 
  st_centroid() |>
  write_sf("data/refugees_country_centroids.geojson")
```

. . .

Import data on refugees by country with the following code:
```{r}
refugees_by_country <-
  read_sf(
    "https://raw.githubusercontent.com/rfortherestofus/mapping-with-r-v2/refs/heads/main/data/refugees.geojson"
  )
```

. . .

Use this code to import centroids (i.e. one point in the center of each country)

```{r}
refugees_country_centroids <-
  read_sf(
    "https://raw.githubusercontent.com/rfortherestofus/mapping-with-r-v2/refs/heads/main/data/refugees_country_centroids.geojson"
  )
```

::: {.notes}
```{r}
#| eval: false
ggplot() +
  geom_sf(data = refugees_by_country) +
  geom_sf(data = refugees_country_centroids, aes(size = number_of_refugees))
```
:::


## Learn More

- Spike maps: https://www.youtube.com/watch?v=qTDf5VVnjMM 
- also https://bsky.app/profile/higsch.com/post/3lgzm5mftyc2x